[build]
      publish = "_site" # Der Standard-Output-Ordner von Jekyll
      functions = "netlify/functions" # Ordner, in dem sich die Funktionen befinden

    # Optional: Wenn Sie spezifische Node.js-Versionen ben√∂tigen
    [build.environment]
      NODE_VERSION = "18"
